=== gallypette/SCREAM-Assistant/app/schemas/creamtable.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cream (information,category+)>
<!ATTLIST cream
  xmlns CDATA #FIXED ''>

<!ELEMENT information (name,desc)>
<!ATTLIST information
  xmlns CDATA #FIXED ''>

<!ELEMENT category (name,desc,group+)>
<!ATTLIST category
  xmlns CDATA #FIXED ''>

<!ELEMENT group (name,desc,gc+)>
<!ATTLIST group
  xmlns CDATA #FIXED ''>

<!ELEMENT gc (name,desc,ga+,sa+,sc+)>
<!ATTLIST gc
  xmlns CDATA #FIXED ''>

<!ELEMENT ga (name,desc)>
<!ATTLIST ga
  xmlns CDATA #FIXED ''>

<!ELEMENT sa (name,desc)>
<!ATTLIST sa
  xmlns CDATA #FIXED ''>

<!ELEMENT sc (name,desc)>
<!ATTLIST sc
  xmlns CDATA #FIXED ''>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  xmlns CDATA #FIXED ''>

<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc
  xmlns CDATA #FIXED ''>

=== gallypette/SCREAM-Assistant/app/schemas/creamtable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cream SYSTEM "creamtable.dtd">
<cream>
	<information>
		<name>CREAM Tables</name>
		<desc>Original tables from Hollnagel's book</desc>
	</information>

	<category>
		<name>Error modes</name>
		<desc/>

		<group>
			<name>Error modes</name>
			<desc/>

			<gc>
				<name>Timing</name>
				<desc>Does the control of the process require timing of actions? Are there clear
					indicators / signals for the timing of actions? Does the system include lead
					time indications? Does a signal clearly indentify the corresponding
					action?</desc>

				<ga>
					<name>Communication failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Faulty diagnosis</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate plan</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate procedure</name>
					<desc/>
				</ga>

				<ga>
					<name>Inattention</name>
					<desc/>
				</ga>

				<ga>
					<name>Observation missed</name>
					<desc/>
				</ga>

				<sa>
					<name>Earlier omission</name>
					<desc/>
				</sa>

				<sa>
					<name>Trapping error</name>
					<desc/>
				</sa>

				<sc>
					<name>Too early</name>
					<desc>An action started too early, before a signal was given or the required
						conditions had been established. (Premature action)</desc>
				</sc>

				<sc>
					<name>Too late</name>
					<desc>An action started too late. (Delayed action)</desc>
				</sc>

				<sc>
					<name>Omission</name>
					<desc>An action that was not done at all (within the time interval
						allowed).</desc>
				</sc>
			</gc>

			<gc>
				<name>Duration</name>
				<desc>Is duration a control parameter? Is duration controlled manually or
					automatically? Is the duration clearly shown or indicated? Does the indication
					show elapsed time or remaining time, or both?</desc>

				<ga>
					<name>Communication failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Faulty diagnosis</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate plan</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate procedure</name>
					<desc/>
				</ga>

				<ga>
					<name>Inattention</name>
					<desc/>
				</ga>

				<ga>
					<name>Observation missed</name>
					<desc/>
				</ga>

				<sa>
					<name>Earlier omission</name>
					<desc/>
				</sa>

				<sa>
					<name>Trapping error</name>
					<desc/>
				</sa>

				<sc>
					<name>Too long</name>
					<desc>An action that was continued beyond the point when it should have
						stopped</desc>
				</sc>

				<sc>
					<name>Too short</name>
					<desc>An action that was stopped before it should have been.</desc>
				</sc>
			</gc>

			<gc>
				<name>Force</name>
				<desc>Is level of force / effort a control parameter? Is the required / applied
					level of force clearly indicated? Is there a minimum/maximum limit of force for
					a control? Can force be controlled without changing position?</desc>

				<ga>
					<name>Communication failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Equipment failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Faulty diagnosis</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate plan</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate procedure</name>
					<desc/>
				</ga>

				<ga>
					<name>Observation missed</name>
					<desc/>
				</ga>

				<sa>
					<name>Ambiguous label</name>
					<desc/>
				</sa>

				<sa>
					<name>Convention conflict</name>
					<desc/>
				</sa>

				<sa>
					<name>Incorrect label</name>
					<desc/>
				</sa>

				<sc>
					<name>Too little</name>
					<desc>Insufficient force.</desc>
				</sc>

				<sc>
					<name>Too much</name>
					<desc>Surplus force, too much effort.</desc>
				</sc>
			</gc>

			<gc>
				<name>Distance / magnitude</name>
				<desc>Is distance or magnitude a control paremeter? Is the required / applied
					distance or magnitude clearly indicated? Can distance / magnitude be controlled
					without changing position?</desc>

				<ga>
					<name>Communication failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Equipment failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Faulty diagnosis</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate plan</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate procedure</name>
					<desc/>
				</ga>

				<ga>
					<name>Observation missed</name>
					<desc/>
				</ga>

				<sa>
					<name>Ambiguous label</name>
					<desc/>
				</sa>

				<sa>
					<name>Convention conflict</name>
					<desc/>
				</sa>

				<sa>
					<name>Incorrect label</name>
					<desc/>
				</sa>

				<sc>
					<name>Too far</name>
					<desc>A movement taken too far.</desc>
				</sc>

				<sc>
					<name>Too short</name>
					<desc>A movement not taken far enough</desc>
				</sc>
			</gc>

			<gc>
				<name>Speed</name>
				<desc>Is speed a control parameter? Is speed controlled manually or automatically
					(set-point / rate)? Is the required / applied speed clearly indicated?</desc>

				<ga>
					<name>Communication failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Distraction</name>
					<desc/>
				</ga>

				<ga>
					<name>Equipment failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Faulty diagnosis</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate plan</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate procedure</name>
					<desc/>
				</ga>

				<ga>
					<name>Observation missed</name>
					<desc/>
				</ga>

				<ga>
					<name>Performance variability</name>
					<desc/>
				</ga>

				<sa>
					<name>None defined</name>
					<desc/>
				</sa>

				<sc>
					<name>Too fast</name>
					<desc>Action performed too quickly, with too much speed or finished too
						early.</desc>
				</sc>

				<sc>
					<name>Too slow</name>
					<desc>Action performed too slowly, with too little speed or finished too
						late.</desc>
				</sc>
			</gc>

			<gc>
				<name>Direction</name>
				<desc>Is direction a control parameter? Is there a direct relation between
					(movement) direction of controls and direction of system response? Is the
					required / applied direction clearly indicated?</desc>

				<ga>
					<name>Communication failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Faulty diagnosis</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate plan</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate procedure</name>
					<desc/>
				</ga>

				<ga>
					<name>Inattention</name>
					<desc/>
				</ga>

				<ga>
					<name>Observation missed</name>
					<desc/>
				</ga>

				<sa>
					<name>Ambiguous label</name>
					<desc/>
				</sa>

				<sa>
					<name>Convention conflict</name>
					<desc/>
				</sa>

				<sa>
					<name>Incorrect label</name>
					<desc/>
				</sa>

				<sc>
					<name>Wrong direction</name>
					<desc>Movement in the wrong direction, e.g. forwards instead of backwards or
						left instead of right.</desc>
				</sc>

				<sc>
					<name>Wrong movement type</name>
					<desc>The wrong kind of movement, such as pulling a knob instead of turning
						it.</desc>
				</sc>
			</gc>

			<gc>
				<name>Wrong object</name>
				<desc>Are different objects clearly separated or coded (colour/shape)? Are objects
					clearly and uniquely identified? Can objects easily be reached and seen when use
					is required?</desc>

				<ga>
					<name>Access problems</name>
					<desc/>
				</ga>

				<ga>
					<name>Communication failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Wrong identification</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate plan</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate procedure</name>
					<desc/>
				</ga>

				<ga>
					<name>Inattention</name>
					<desc/>
				</ga>

				<ga>
					<name>Performance variability</name>
					<desc/>
				</ga>

				<ga>
					<name>Observation missed</name>
					<desc/>
				</ga>

				<sa>
					<name>Ambiguous label</name>
					<desc/>
				</sa>

				<sa>
					<name>Incorrect label</name>
					<desc/>
				</sa>

				<sc>
					<name>Neighbor</name>
					<desc>An object that is in physical proximity to the object that should have
						been used.</desc>
				</sc>

				<sc>
					<name>Similar object</name>
					<desc>An object that is similar in appearance to the object that should have
						been used.</desc>
				</sc>

				<sc>
					<name>Unrelated object</name>
					<desc>An object that was used by mistake, even though it had no obvious relation
						to the object that should have been used</desc>
				</sc>
			</gc>

			<gc>
				<name>Sequence</name>
				<desc>Is the sequence of actions / next action clearly indicated? Is the direction
					of the sequence reversible? Can out-of-sequence actions easily be
					recovered?</desc>

				<ga>
					<name>Access limitations</name>
					<desc/>
				</ga>

				<ga>
					<name>Communication failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Faulty diagnosis</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate plan</name>
					<desc/>
				</ga>

				<ga>
					<name>Inadequate procedure</name>
					<desc/>
				</ga>

				<ga>
					<name>Inattention</name>
					<desc/>
				</ga>

				<ga>
					<name>Memory failure</name>
					<desc/>
				</ga>

				<ga>
					<name>Wrong identification</name>
					<desc/>
				</ga>

				<sa>
					<name>Trapping error</name>
					<desc/>
				</sa>

				<sc>
					<name>Omission</name>
					<desc>An action that was not carried out. This includes in particular the
						omission of the last action(s) of a series</desc>
				</sc>

				<sc>
					<name>Jump forward</name>
					<desc>One or more actions in a sequence were skipped.</desc>
				</sc>

				<sc>
					<name>Jump backwards</name>
					<desc>One or more earlier actions that have been carried out, is carried out
						again.</desc>
				</sc>

				<sc>
					<name>Repetition</name>
					<desc>The previous action is repeated.</desc>
				</sc>
